version: '3.3'

services:
  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - web
    expose:
      - 5432
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: 'codedeploy/Dockerfile'
    ports:
      - '4000:4000'
    env_file:
      - .env
    networks:
      - web

networks:
  web:
    external: true
